### ISSUE TITLE
Configure option for Wire1

### ISSUE THREAD

**Issue by fletchjp** [dantudose/AT24C256#2]
Dan  Thank you for your library. It has been what enabled me to get going with my AT24C256 boards. I now have examples running on a MEGA having sorted out read and write from your code.

I would like to use the library on an Arduino DUE where I am using Wire1 instead of Wire. Is it possible to have a version where WIRE can be configured by the user?

Thanks John Fletcher

**Comment by dantudose** [comment]
Glad you're finding my code useful. I modified it so that it should work with any Wire interface, but I did not have time to properly test it on actual hardware. If you want to use Wire1 instead of Wire, just modify line 3 in the read_write.ino example:
AT24C256 eeprom(0x50, &Wire1);

Please do let me know if you test it on actual hardware and it doesn't work.

Cheers,
Dan

**Comment by fletchjp** [comment]
Dan  Thank you very much. Your modified version works fine for Wire and fails on Wire1.

I looked at this last night and found out that the problem was in the constructor. The solution was to remove the call to begin() from the constructor. I created a new member function begin() in the class and when it is called in the setup() routine everything works.

The reason for the problem must be buried somewhere in the Wire library.

I don't have things set up to push changes to you - I am working across two computers.

Thanks again

John

**Comment by fletchjp** [comment]
This does the job in AT24C256.cpp

void AT24C256::begin()
{
     _twi->begin();
}

John

**Comment by fletchjp** [comment]
It is also possible to add = &Wire as a default so that the previous constructor still works - I have checked that.

Unfortunately having to add  eeprom.begin() will break previous examples.

John

**Comment by dantudose** [comment]
Ok, I made the modifications you suggested and there's now a begin() function. Got around to test it with Wire and Wire1, both compile just fine on my machine.

**Comment by flavios55** [comment]
I have a MKR1010 and the system locks up and disconnects from the USB just with your sample. Address I2C discovery is ok. It works fine on Arduino UNO and it works fine if I use only Wire.h commands. Your library would make my life much easier, though... 
Tks
Flavio

**Comment by dantudose** [comment]
Unfortunately I don't have a MKR1010 in order to test and try to replicate your problem. Most of the testing I've done was on UNO and ESP32 boards.

**Comment by flavios55** [comment]
Many thanks, Dan. "Work-around" is our motto ;-)
Flavio
