### ISSUE TITLE
Compiler warning for requestFrom call - program still properly compiles

### ISSUE THREAD

**Issue by generically-named** [dantudose/AT24C256#4]
Hi, I'm new to Github/Arduino libraries and so if I haven't included all relevant info please let me know. I encountered the below compiler warning when running the example provided for the library. The program will still run and function fine. I fixed my version of the library by editing line 31 of the AT24C256.cpp file from:
`Wire.requestFrom(_address, len);`
to
`Wire.requestFrom((uint8_t)_address, (uint8_t)len);`

I am using the latest version in the Arduino IDE (1.0.0). The IDE (version 2.2.1) is running on Arch Linux (Kernel 6.1.53-1) if this makes any difference.

Is this an actual issue to be solved in the program or is my compiler being overzealous in warning me about this?

The compiler error I get:
`In file included from /home/{username}/Arduino/libraries/AT24C256_library/src/AT24C256.cpp:3:0:
/home/{username}/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/Wire.h: In member function 'void AT24C256::read(uint16_t, uint8_t*, uint8_t)':
/home/{username}/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/Wire.h:68:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
     uint8_t requestFrom(int, int);
             ^~~~~~~~~~~
/home/{username}/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/Wire.h:65:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t);
             ^~~~~~~~~~~
`

**Comment by dantudose** [comment]
Fixed.
